@startuml
hide footbox
title sdk-server交互
App -> SDK: 注册
SDK -[#0FFF00]-> Server: 接口[初始化]
SDK -[#0FFF00]-> Server: 接口[拿Access_Token]
Server --> SDK: Access_Token
SDK --> SDK: 本地缓存Access_Token
App -> SDK:打开模块
SDK -[#0FFF00]-> Server: 接口[查模块h5地址]
Server --> SDK: 模块h5地址
SDK -> App: 加载h5
@enduml

