/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangli_jni_myjni_MyJNIDemo */

#ifndef _Included_com_jiangli_jni_myjni_MyJNIDemo
#define _Included_com_jiangli_jni_myjni_MyJNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangli_jni_myjni_MyJNIDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jiangli_jni_myjni_MyJNIDemo_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
