package com.jiangli.practice.test;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.sql.*;

/**
 * @author Jiangli
 * @date 2017/4/18 11:11
 */
public class DerbyTest {
    private long startTs;

    @Before
    public void before() {
        startTs = System.currentTimeMillis();
        System.out.println("----------before-----------");
        System.out.println();
    }

    @After
    public void after() {
        long cost = System.currentTimeMillis() - startTs;
        System.out.println("----------after-----------:cost:" + cost + " ms");
        System.out.println();
    }

    @Test
    public void test_as() {
        String driver = "org.apache.derby.jdbc.EmbeddedDriver";
//        String url = "jdbc:derby:firstdb;create=true";
        String protocol="jdbc:derby:";
        String suffix=";create=true";
//        String suffix=";";
//        jdbc:derby:d:/temp/test;create=true

        //use Database of Intellij IDE
        //D:\algorithem\Practice\src\main\resources\db
//        String dbName= PathUtil.buildPath(PathUtil.getProjectPath("Practice").getProjectBasePath(), false,PathUtil.PATH_SRC_MAIN_RESOURCES,"db");
        String dbName= "D:\\algorithem\\Practice\\src\\main\\resources\\db";
        String url = protocol+dbName+suffix;
        //jdbc:derby:D:\algorithem\Practice\src\main\resources\db;create=true
        System.out.println(url);

        Connection conn;
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url);

            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * from APP.MERCHANT");
            while (resultSet.next()) {
                System.out.println(resultSet.getString("name"));
            }
        }catch(Exception e) {
            e.printStackTrace();
        }finally {
            try {
                DriverManager.getConnection("jdbc:derby:;shutdown=true");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

//    “GENERATED ALWAYS AS IDENTITY” – Derby always provides auto-incremented sequence values to this column. You are not allowed to specify your own values. 由Derby负责提供自增的主键值, 该值不允许插入.
//“GENERATED BY DEFAULT AS IDENTITY” – Derby provides auto-incremented sequence values to this as default only when you are not providing values. 仅在未提供主键值时, 由Derby负责插入.
    //INSERT INTO APP.MERCHANT(NAME) VALUES('浏阳蒸菜');

    //INSERT INTO APP.DISH(NAME, MONEY, PACKAGE, MERCHANTID) VALUES ('米饭',2,1,1)

    //INSERT INTO APP.RULE(NAME, MONEY, PACKAGE, MERCHANTID) VALUES ('米饭',2,1,1)

    //DISH
}
